name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "If you need fast help join the server https://discord.gg/qvkC6kHqer"
        pr-message: "Thank you for making a pr. Your prolly the first person to actually do that!"
